backend:
  name: github
  repo: brenonovelli/praca-seca
  branch: master
  site_domain: www.pracaseca.com.br

publish_mode: editorial_workflow
media_folder: 'static/assets/img'
public_folder: 'assets/img'

slug:
  encoding: 'ascii'
  clean_accents: true

collections:
  - name: 'business' # Used in routes, e.g., /admin/collections/blog
    label: 'Negócio' # Used in the UI
    folder: 'posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - {
          label: 'Categoria',
          name: 'category',
          widget: 'select',
          options:
            [
              { label: 'Alimentação', value: 'Alimentação' },
              { label: 'Confeitaria', value: 'Confeitaria' },
              {
                label: 'Construção e reformas',
                value: 'Construção e reformas',
              },
              { label: 'Educação', value: 'Educação' },
              { label: 'Estética e Beleza', value: 'Estética e Beleza' },
              { label: 'Informática', value: 'Informática' },
              { label: 'Lojas e Comércios', value: 'Lojas e Comércios' },
              { label: 'Saúde', value: 'Saúde' },
              {
                label: 'Serviços Profissionais',
                value: 'Serviços Profissionais',
              },
            ],
        }
      - {
          label: 'Subcategoria',
          name: 'subcategory',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          required: false,
        }
      - {
          label: 'Região',
          name: 'zone',
          widget: 'select',
          options:
            [
              { label: 'Centro', value: 'Centro' },
              { label: 'Chacrinha', value: 'Chacrinha' },
              {
                label: 'Ipase - Batô (Bateau Mouche)',
                value: 'Ipase - Batô (Bateau Mouche)',
              },
              { label: 'Próximo ao Campinho', value: 'Próximo ao Campinho' },
              { label: 'Próximo ao Valqueire', value: 'Próximo ao Valqueire' },
              { label: 'Campinho', value: 'Campinho' },
              { label: 'Valqueire', value: 'Valqueire' },
              { label: 'Tanque', value: 'Tanque' },
              { label: 'Taquara', value: 'Taquara' },
            ],
        }
      - {
          label: 'Endereço',
          name: 'address',
          widget: 'string',
          required: false,
        }
      - { label: 'E-mail', name: 'email', widget: 'string', required: false }
      - { label: 'Site', name: 'site', widget: 'string', required: false }
      - {
          label: 'Telefone',
          name: 'telefone',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Whatsapp',
          name: 'whatsapp',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Instagram',
          name: 'instagram',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Facebook',
          name: 'facebook',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Entregas ou atendimento presencial',
          name: 'delivery',
          widget: 'select',
          options:
            [
              { label: 'Entrega', value: 1 },
              { label: 'Presencial', value: 2 },
              { label: 'Não', value: 3 },
            ],
        }
      - { label: 'image', name: 'thumbnail', widget: 'image', required: false }
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD hh:mm:ss',
        }
      - {
          label: 'Background',
          name: 'background',
          widget: 'select',
          required: false,
          options:
            [
              { label: 'Geral', value: '#B31917' },
            ],
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
